# Generated by Django 5.1.2 on 2024-11-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Загрузите фото')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название книги')),
                ('description', models.TextField(default='Lorem ipsum', verbose_name='Укажите описание книги')),
                ('price', models.FloatField(verbose_name='Укажите цену')),
                ('start_book', models.DateField(verbose_name='Укажите дату выхода')),
                ('genre', models.CharField(choices=[('Детектив', 'Детектив'), ('Любовный роман', 'Любовный роман'), ('Фантастика', 'Фантастика'), ('Мистика', 'Мистика'), ('Исторический роман', 'Исторический роман'), ('Авантюрны', 'Авантюрны')], default='Фантастика', max_length=100, verbose_name='Укажите жанр')),
                ('gmail', models.EmailField(max_length=254, verbose_name='Укажите почту автора')),
                ('author', models.CharField(max_length=40, verbose_name='Укажите автора')),
            ],
        ),
    ]
