# Generated by Django 5.1.2 on 2024-11-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0003_rename_review_film_reviewbook_review_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Укажите имя заказчика')),
                ('phone_number', models.IntegerField(verbose_name='Укажите номер телефона заказчика')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main_page.library', verbose_name='Укажите книгу')),
            ],
        ),
    ]
